export class  IntakeForm {
    // id:String; generated by server
    //A
    principalInvestigator:String;
    department:String;
    college:String;//can be found from department
    projectTitle:String;
    proposedFundingAmount:String;
    startDate:Date;
    endDate:Date;
    //B 
    personnel:Personnel[];//personnel object
    //C
    anticipateStipend:Boolean;
    stipends:String;
    facultyStudentResearchCreativeActivities:Boolean;
    studentsInResearch:Boolean;
    noOfUndergradStudents:Number;
    noOfGradStudents:Number
    laboratoryAssitance:Boolean;
    dataCollection:Boolean;
    reportWriting:Boolean;
    literatureReview:Boolean;
    codingOrDataEntry:Boolean;
    presentation:Boolean;
    archivalResearch:Boolean;
    dataAnalysis:Boolean;
    otherActivities:Boolean;
    otherActivitiesList:String[];
    //D
    subGrantsOrSubContracts:SubgrantSubProject[];//subgrantsubcontract
    //E
    projectLocations:ProjectLocation[];//projectLocation
    //F
    additionalInvolvedParties:AdditionalParty[];//additionalparty
    //G
    agencyCostRatePercentage;
    agencyCostSharing:Boolean;
    piCostSharing:Boolean;
    computersRequested:Number;
    requestedEquipment:any;//map<string,double>
    //H
    spaces:any[];//space
    //I
    hazardousSubstances:any[];//<String,String>
    //J
    humanSubject:Boolean;
    vertebrateAnimals:Boolean;
    questionareField:String;
    categoryTitle:String;
    //K
    assistanceWithProposalDevelopment:Boolean;
    technicalAssistance:Boolean;
    letterOfSupportPresident:Boolean;
    letterOfSupportProvost:Boolean;
    letterOfSupportAssocVPOfResearch:Boolean;
    duplicationfFinalDocumentPackage:Boolean;
    noOfCopies:Number;
    //L
    summary:String;
    constructor(){}
} 
 class Personnel
{
    name:String;
    employer:String;
    positionTitleOnGrant:String;
    units:String;
}
class SubgrantSubProject{
    institutionName:String;
    proposedFundingAmount:Number;
    contactPerson:String;
    contactInfo:String;  
}
class ProjectLocation {
    siteName:String;
    siteAddress:String;
    projectedPercentOfTimeAtState:String;
    onCampusSpaceOrOnCampusRentalNeeded:Boolean;
}
class AdditionalParty{
    partyName:String;
    supervisor:String;
    explanationOfInvolvement:String;
}